apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmapvolumedeployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: bb-container
        image: suyogkharage/envconfigmap:v0
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config	
      volumes:
      - name: config-volume
        configMap:
           name: game-demo
---
apiVersion: v1
kind: Service
metadata:
  name: configmapvolumeservice
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  # file-like keys
  game.properties.conf: |
    enemy.types=aliens,monsters
    player.maximum-lives=5
  user-interface.properties.conf: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true